### ISSUE TITLE
just curious

### ISSUE THREAD

**Issue by stobenski** [tell-k/vim-quick-radon#3]
Hi, thanks for plugin, just curious: what colorscheme do you use?
![](https://camo.githubusercontent.com/304a5f3f31812afd7e8fa59bac2467d2a6411b2d/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f7370612f6768796e3837796234656a6e3579792f722d7032777a64782e706e67)
I checked your .vimrc in dotfiles repo, there configured zellner, but zellner is different colorscheme compared to picture above.

Thanks.

**Comment by tell-k** [comment]
Hi. @barwinco

As you have guessed, my colorscheme is "zellner".
Sorry, i do not know the difference between yours and mine.
I am running vim on Terminal.app of OS X. 

I hope you find it informative. 
Thx.

**Comment by tell-k** [comment]
@barwinco 

Maybe Terminal color settings might difference is between me and you. 
I changed color settings from Novel to Pro. Then, different even same zellner.

![](https://dl.dropboxusercontent.com/spa/ghyn87yb4ejn5yy/0dustbwi.png)

**Comment by stobenski** [comment]
Thanks.
